name: linux_test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: wget linux zip file
        run: |
          wget https://github.com/kimsinhyun/linux/archive/ec5450256b.zip
          
         

#       # Runs a set of commands using the runners shell
      - name: unzip linux zip
        run: unzip ec5450256b.zip
        
      - name: install gcc-8
        run: | 
          sudo apt-get update
          sudo apt-get install gcc-8
          
    
      - name: build linux
        shell: bash
        run: ./build-linux.sh linux-ec5450256b468e4c9a8d939555acb3afc96796da
