name: linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Install Dependencies
        shell: bash
        run: |
          ./install-deps.sh
          
      - name: Get the commit number of Linux Repo(submodule) & Download the zip file & unzip zip file
        shell: bash
        run: |
          Submodule_commit_Num=$(git submodule status | awk '{print $1}' | cut -c -10)
          wget https://github.com/kimsinhyun/linux/archive/$Submodule_commit_Num.zip
          unzip $Submodule_commit_Num.zip        
    
      - name: build linux
        shell: bash
        run: |
          Submodule_commit_Num_2="$(git submodule status | awk '{print $1}')"
          Submodule_commit_Num_2="linux-${Submodule_commit_Num_2}"
          ./build-linux.sh $Submodule_commit_Num_2 tinyconfig
