
# This is a basic workflow to help you get started with Actions

name: test

on: [push]


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Compile the test cases
        run: make -C test
